import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

const baseStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.surfaceScrim,
  },
  scroll: {
    flex: 1,
    zIndex: 5,
    backgroundColor: 'transparent',
  },
  homeWallpaper: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
    gap: 22,
  },
  hero: {
    borderRadius: 28,
    minHeight: 200,
    overflow: 'hidden',
    backgroundColor: colors.primaryContainer,
  },
  heroImage: {
    ...StyleSheet.absoluteFillObject,
  },
  heroContent: {
    padding: 20,
    minHeight: 200,
    justifyContent: 'space-between',
    zIndex: 1,
  },
  heroTitle: {
    color: colors.textPrimary,
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '700',
    maxWidth: 280,
  },
  heroTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  heroTagSecondary: {
    color: colors.secondary,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    borderWidth: 1,
    borderColor: colors.chipSecondaryBorder,
    backgroundColor: colors.chipSecondaryBg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    letterSpacing: 1,
  },
  heroTagPrimary: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    borderWidth: 1,
    borderColor: colors.chipPrimaryBorder,
    backgroundColor: colors.chipPrimaryBg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    letterSpacing: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  sectionAction: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '700',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  categoryCard: {
    width: '48%',
    backgroundColor: colors.surfaceLow,
    borderRadius: 22,
    paddingVertical: 20,
    paddingHorizontal: 12,
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
  },
  categoryIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.categoryIconTint,
  },
  categoryIcon: {
    color: colors.primary,
    fontSize: 28,
    fontWeight: '700',
  },
  categoryLabel: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '600',
  },
  featuredList: {
    gap: 14,
  },
  featuredCard: {
    borderRadius: 28,
    backgroundColor: colors.surfaceLow,
    padding: 14,
    flexDirection: 'row',
    gap: 14,
    alignItems: 'stretch',
    borderWidth: 1,
    borderColor: colors.outlineVariant,
  },
  featuredThumbColumn: {
    alignItems: 'center',
    gap: 6,
    justifyContent: 'flex-start',
  },
  featuredMedia: {
    width: 108,
    height: 136,
    borderRadius: 18,
    backgroundColor: colors.surfaceMuted,
    overflow: 'hidden',
  },
  featuredThumbImage: {
    width: '100%',
    height: '100%',
  },
  featuredRate: {
    color: colors.onSecondary,
    backgroundColor: colors.secondary,
    fontWeight: '700',
    fontSize: 12,
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    overflow: 'hidden',
  },
  featuredContent: {
    flex: 1,
    gap: 8,
  },
  featuredBadge: {
    color: colors.secondary,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  featuredTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  featuredDescription: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  featuredMeta: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  featuredPrice: {
    color: colors.primary,
    fontWeight: '700',
  },
  featuredDuration: {
    color: colors.textSecondary,
    fontSize: 11,
    textTransform: 'uppercase',
    borderWidth: 1,
    borderColor: colors.primaryOutlineFaint,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
});

export const styles = baseStyles;
