import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
    gap: 22,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  brandIcon: {
    color: colors.primary,
    fontSize: 18,
  },
  brandText: {
    color: colors.secondary,
    fontSize: 24,
    fontWeight: '700',
    fontStyle: 'italic',
    letterSpacing: 2,
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  topAction: {
    color: colors.textSecondary,
    fontSize: 18,
  },
  avatarPlaceholder: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#4a4550',
  },
  avatarText: {
    color: colors.textPrimary,
    fontWeight: '700',
    fontSize: 12,
  },
  hero: {
    borderRadius: 28,
    padding: 20,
    minHeight: 198,
    justifyContent: 'space-between',
    backgroundColor: '#2d0b5a',
    overflow: 'hidden',
  },
  heroGlow: {
    position: 'absolute',
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: colors.primary,
    opacity: 0.2,
    right: -40,
    top: -40,
  },
  heroTitle: {
    color: colors.textPrimary,
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '700',
    maxWidth: 280,
  },
  heroTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  heroTagSecondary: {
    color: colors.secondary,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    borderWidth: 1,
    borderColor: 'rgba(233,195,73,0.35)',
    backgroundColor: 'rgba(233,195,73,0.08)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    letterSpacing: 1,
  },
  heroTagPrimary: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    borderWidth: 1,
    borderColor: 'rgba(214,186,255,0.35)',
    backgroundColor: 'rgba(214,186,255,0.08)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    letterSpacing: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  sectionAction: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  title: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '700',
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '700',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  categoryCard: {
    width: '48%',
    backgroundColor: '#151a31',
    borderRadius: 22,
    paddingVertical: 20,
    paddingHorizontal: 12,
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: '#4a4550',
  },
  categoryIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(45,11,90,0.35)',
  },
  categoryIcon: {
    color: colors.primary,
    fontSize: 28,
    fontWeight: '700',
  },
  categoryLabel: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '600',
  },
  featuredList: {
    gap: 14,
  },
  featuredCard: {
    borderRadius: 28,
    backgroundColor: '#151a31',
    padding: 14,
    flexDirection: 'row',
    gap: 14,
    borderWidth: 1,
    borderColor: '#4a4550',
  },
  featuredMedia: {
    width: 92,
    borderRadius: 18,
    backgroundColor: '#2f334b',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 10,
    paddingHorizontal: 8,
  },
  featuredRate: {
    color: colors.onSecondary,
    backgroundColor: colors.secondary,
    fontWeight: '700',
    fontSize: 12,
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    overflow: 'hidden',
  },
  featuredContent: {
    flex: 1,
    gap: 8,
  },
  featuredBadge: {
    color: colors.secondary,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  featuredTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  featuredDescription: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  featuredMeta: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  featuredPrice: {
    color: colors.primary,
    fontWeight: '700',
  },
  featuredDuration: {
    color: colors.textSecondary,
    fontSize: 11,
    textTransform: 'uppercase',
    borderWidth: 1,
    borderColor: 'rgba(214,186,255,0.25)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
});
