import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { FONT_FAMILIES } from '../../theme/fonts';

export const CHAT_NEBULA_URI =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCmjymvr-bW6wJhGdx3j-NHT3ey737VK-EtC8THDfes2GP6MziYyA6LGdVkLAFFXqKx7q6w2JGys2bO7WIHqAXmBZJeqMwcI9L8w-7ocx-L5olcmfbt_19syfDXUCRTVe3urSRv7Hvom84rsuS7G4KlyHUSkmQ0pgigu62mlBSZK4EuV17YxUo-wJs6G236pYb4ofsI6EJ7aPswoYOkGK4B5MVSaHEg29-cfCXiKXXxtVygvlcAGmlNNijmh071GUOueas0gngrleA';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  bgImage: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.3,
  },
  bgGradientTop: {
    ...StyleSheet.absoluteFillObject,
  },
  atmosphereTop: {
    position: 'absolute',
    top: '22%',
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(214, 186, 255, 0.06)',
  },
  atmosphereBottom: {
    position: 'absolute',
    bottom: '18%',
    left: -40,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: 'rgba(233, 195, 73, 0.05)',
  },
  headerOuter: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    overflow: 'hidden',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(168, 85, 247, 0.2)',
  },
  headerScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.surfaceLowest,
  },
  headerBlurLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 8,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flex: 1,
    minWidth: 0,
  },
  headerBack: {
    padding: 4,
  },
  headerIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  headerAvatarWrap: {
    position: 'relative',
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(233, 195, 73, 0.3)',
  },
  headerAvatarImage: {
    width: '100%',
    height: '100%',
  },
  headerOnlineDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.secondary,
    borderWidth: 2,
    borderColor: colors.background,
  },
  headerTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    color: 'rgba(196, 181, 253, 0.95)',
    fontSize: 18,
    lineHeight: 22,
    fontFamily: FONT_FAMILIES.semiBold,
    letterSpacing: 0.5,
  },
  headerSubtitle: {
    marginTop: 2,
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 1.6,
    color: 'rgba(148, 163, 184, 0.95)',
    fontFamily: FONT_FAMILIES.medium,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  headerIconHit: {
    padding: 4,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: 24,
    paddingBottom: 120,
    gap: 32,
  },
  datePillWrap: {
    alignItems: 'center',
    marginBottom: 8,
  },
  datePill: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.surfaceLow,
    borderWidth: 1,
    borderColor: 'rgba(168, 85, 247, 0.12)',
  },
  datePillText: {
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 2,
    color: 'rgba(148, 163, 184, 0.95)',
    fontFamily: FONT_FAMILIES.medium,
  },
  bubbleRow: {
    maxWidth: '85%',
    gap: 8,
  },
  bubbleRowClient: {
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
  },
  bubbleRowPro: {
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
  },
  bubblePro: {
    backgroundColor: colors.primaryContainer,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    overflow: 'hidden',
    shadowColor: colors.shadowVioletDeep,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 6,
  },
  bubbleProText: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: FONT_FAMILIES.regular,
    color: colors.secondary,
  },
  bubbleProTextItalic: {
    fontFamily: FONT_FAMILIES.boldItalic,
    fontStyle: 'italic',
  },
  bubbleClient: {
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(168, 85, 247, 0.12)',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 8,
  },
  bubbleClientText: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: FONT_FAMILIES.regular,
    color: 'rgba(233, 213, 255, 0.98)',
  },
  metaPro: {
    marginLeft: 4,
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: 'rgba(148, 163, 184, 0.9)',
    fontFamily: FONT_FAMILIES.medium,
  },
  metaClientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginRight: 4,
  },
  metaClient: {
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: 'rgba(148, 163, 184, 0.9)',
    fontFamily: FONT_FAMILIES.medium,
  },
  footerOuter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  footerBlur: {
    width: '100%',
    maxWidth: 672,
    borderRadius: 999,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(168, 85, 247, 0.2)',
    shadowColor: 'rgba(13, 18, 40, 0.85)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 40,
    elevation: 12,
  },
  footerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  attachHit: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    color: colors.textPrimary,
    fontSize: 14,
    fontFamily: FONT_FAMILIES.regular,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(233, 195, 73, 0.45)',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 4,
  },
  sendButtonDisabled: {
    opacity: 0.42,
  },
});
