import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.surfaceScrim,
  },
  profileWallpaper: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  scroll: {
    flex: 1,
    zIndex: 5,
    backgroundColor: 'transparent',
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 108,
    gap: 28,
    maxWidth: 480,
    width: '100%',
    alignSelf: 'center',
  },
  profileHeader: {
    alignItems: 'center',
  },
  avatarFrameOuter: {
    width: 120,
    height: 120,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFrameGradient: {
    width: 120,
    height: 120,
    borderRadius: 60,
    padding: 4,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 16,
    elevation: 8,
  },
  avatarInnerRing: {
    width: 112,
    height: 112,
    borderRadius: 56,
    overflow: 'hidden',
    borderWidth: 4,
    borderColor: colors.background,
    backgroundColor: colors.background,
  },
  avatarImage: {
    width: 112,
    height: 112,
  },
  avatarBadge: {
    position: 'absolute',
    right: 0,
    bottom: 4,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.textMask,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 6,
  },
  displayName: {
    color: colors.textPrimary,
    fontSize: 32,
    fontWeight: '700',
    letterSpacing: -0.5,
    marginBottom: 10,
    textAlign: 'center',
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.primaryContainer,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.secondary,
  },
  statusPillText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  statCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: 'rgba(25, 30, 53, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(74, 69, 80, 0.35)',
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  statCardHighlight: {
    borderColor: 'rgba(214,186,255,0.25)',
  },
  statValue: {
    color: colors.secondary,
    fontSize: 20,
    fontWeight: '700',
  },
  statLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginTop: 6,
    textAlign: 'center',
  },
  constellationCard: {
    borderRadius: 26,
    backgroundColor: 'rgba(25, 30, 53, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(214,186,255,0.2)',
    padding: 20,
    overflow: 'hidden',
  },
  constellationGlow: {
    position: 'absolute',
    top: -32,
    right: -32,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(233, 195, 73, 0.08)',
  },
  constellationInner: {
    gap: 14,
  },
  constellationTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  constellationTitle: {
    color: colors.secondary,
    fontSize: 20,
    fontWeight: '700',
    fontStyle: 'italic',
  },
  constellationSubtitle: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 4,
    lineHeight: 18,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: colors.surfaceLowest,
    overflow: 'hidden',
  },
  progressFill: {
    width: '85%',
    height: '100%',
    borderRadius: 999,
  },
  constellationHint: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  constellationHintBold: {
    color: colors.secondary,
    fontWeight: '700',
  },
  menuList: {
    gap: 14,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderRadius: 18,
    backgroundColor: colors.surfaceLow,
  },
  menuItemPressed: {
    backgroundColor: colors.surfaceMuted,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    flex: 1,
  },
  menuIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuItemLabel: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.3,
    flex: 1,
  },
  menuChevron: {
    opacity: 0.45,
  },
  footer: {
    alignItems: 'center',
    paddingTop: 12,
    gap: 20,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoutText: {
    color: colors.error,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.6,
  },
  versionText: {
    color: 'rgba(198,198,198,0.35)',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 2,
    textAlign: 'center',
  },
});
