import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.surfaceScrim,
  },
  scroll: {
    flex: 1,
    zIndex: 5,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 108,
    gap: 24,
  },
  brandTitle: {
    color: colors.primary,
    fontSize: 30,
    fontWeight: '700',
    fontStyle: 'italic',
    letterSpacing: 1.8,
  },
  searchInputWrap: {
    borderRadius: 999,
    backgroundColor: colors.surfaceLowest,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    minHeight: 52,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInputIcon: {
    color: colors.textSecondary,
    opacity: 0.9,
  },
  searchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    paddingVertical: 12,
  },
  sectionBlock: {
    gap: 14,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionAction: {
    color: colors.secondary,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  sectionTitleSm: {
    color: colors.primary,
    fontSize: 20,
    fontWeight: '700',
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 26,
    fontWeight: '700',
  },
  chipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  searchChip: {
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    backgroundColor: colors.surface,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  searchChipText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  categoryCard: {
    width: '48%',
    minHeight: 120,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: colors.surfaceLow,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
  },
  categoryIcon: {
    color: colors.secondary,
  },
  categoryLabel: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  featuredCard: {
    backgroundColor: 'rgba(36, 41, 64, 0.7)',
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderRadius: 22,
    padding: 12,
    gap: 12,
  },
  featuredImageLarge: {
    width: '100%',
    height: 190,
    borderRadius: 14,
  },
  featuredCardContent: {
    gap: 8,
  },
  featuredTag: {
    alignSelf: 'flex-start',
    color: colors.secondary,
    borderWidth: 1,
    borderColor: colors.chipSecondaryBorder,
    backgroundColor: colors.chipSecondaryBg,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    letterSpacing: 0.8,
  },
  featuredTitle: {
    color: colors.primary,
    fontSize: 20,
    fontWeight: '700',
  },
  featuredDescription: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  featuredFooter: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  featuredPrice: {
    color: colors.secondary,
    fontSize: 18,
    fontWeight: '700',
  },
  featuredButton: {
    borderRadius: 999,
    backgroundColor: colors.secondary,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  featuredButtonText: {
    color: colors.onSecondary,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  compactCard: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(36, 41, 64, 0.7)',
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderRadius: 22,
    padding: 12,
  },
  compactAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
  },
  compactContent: {
    flex: 1,
    gap: 4,
  },
  compactTitle: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: '700',
  },
  compactDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
  },
  compactMeta: {
    color: colors.secondary,
    fontSize: 11,
    fontWeight: '600',
  },
  compactChevron: {
    color: colors.secondary,
  },
  exploreHero: {
    minHeight: 260,
    borderRadius: 26,
    overflow: 'hidden',
    backgroundColor: colors.surfaceLow,
  },
  exploreHeroImage: {
    ...StyleSheet.absoluteFillObject,
  },
  exploreOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 18,
    paddingVertical: 18,
    backgroundColor: 'rgba(8, 13, 34, 0.48)',
    gap: 5,
  },
  exploreKicker: {
    color: colors.secondary,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  exploreTitle: {
    color: colors.white,
    fontSize: 26,
    fontWeight: '700',
  },
  exploreDescription: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    lineHeight: 18,
  },
});
