import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.surfaceScrim,
  },
  scroll: {
    flex: 1,
    zIndex: 5,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 130,
    gap: 24,
  },
  topBar: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topBarPremium: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(233,195,73,0.16)',
    paddingBottom: 6,
  },
  topBarButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: colors.surfaceLow,
  },
  topBarTitle: {
    color: colors.secondary,
    fontSize: 22,
    fontWeight: '700',
    fontStyle: 'italic',
    letterSpacing: 1.5,
  },
  topBarTitlePremium: {
    letterSpacing: 2.6,
    textTransform: 'uppercase',
  },
  profileSection: {
    alignItems: 'center',
    gap: 10,
  },
  premiumBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(233,195,73,0.32)',
    backgroundColor: 'rgba(233,195,73,0.08)',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  premiumBadgeText: {
    color: colors.secondary,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    fontSize: 10,
    fontWeight: '700',
  },

  avatarFrame: {
    width: 150,
    height: 150,
    borderRadius: 75,
    padding: 4,
  },
  avatarWrap: {
    width: 170,
    height: 170,
    alignItems: 'center',
    justifyContent: 'center',
  },
  premiumHalo: {
    position: 'absolute',
    width: 194,
    height: 194,
    borderRadius: 97,
    alignItems: 'center',
    justifyContent: 'center',
  },
  premiumHaloOuter: {
    position: 'absolute',
    width: 194,
    height: 194,
    borderRadius: 97,
    backgroundColor: 'rgba(233,195,73,0.08)',
  },
  premiumHaloInner: {
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: 'rgba(233,195,73,0.14)',
  },
  avatarFramePremium: {
    shadowColor: colors.secondary,
    shadowOpacity: 0.35,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  avatarFrameInner: {
    width: '100%',
    height: '100%',
    borderRadius: 71,
    overflow: 'hidden',
    borderWidth: 4,
    borderColor: colors.surface,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 70,
    backgroundColor: colors.surfaceMuted,
  },
  name: {
    color: colors.textPrimary,
    fontSize: 34,
    fontWeight: '700',
    textAlign: 'center',
  },
  namePremium: {
    color: colors.secondary,
    fontSize: 38,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  ratingMeta: {
    marginLeft: 8,
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '500',
  },
  specialty: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.3,
  },
  specialtyPremium: {
    color: colors.secondary,
    fontSize: 10,
    letterSpacing: 1.8,
  },
  sectionBlock: {
    gap: 14,
  },
  sectionTitle: {
    color: colors.secondary,
    fontSize: 24,
    fontWeight: '700',
  },
  sectionTitlePremium: {
    letterSpacing: 1.2,
  },
  aboutRow: {
    gap: 14,
  },
  aboutMain: {
    gap: 10,
  },
  scheduleCard: {
    borderRadius: 14,
    backgroundColor: colors.surfaceLow,
    borderWidth: 1,
    borderColor: 'rgba(74,69,80,0.35)',
    padding: 14,
    gap: 10,
  },
  scheduleCardPremium: {
    borderColor: 'rgba(233,195,73,0.35)',
    backgroundColor: 'rgba(25,30,53,0.92)',
  },
  scheduleTitle: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  scheduleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  scheduleDay: {
    color: colors.textSecondary,
    fontSize: 13,
  },
  scheduleTime: {
    color: colors.secondary,
    fontSize: 13,
    fontWeight: '700',
  },
  description: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  specialtyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
  },
  specialtyCard: {
    width: '48%',
    minHeight: 96,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  specialtyCardFeatured: {
    minHeight: 170,
    backgroundColor: colors.surfaceMuted,
    borderColor: 'rgba(214,186,255,0.28)',
  },
  specialtyCardText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  specialtyFeaturedHint: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    textAlign: 'center',
  },
  reviewsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  seeAll: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '600',
  },
  reviewCard: {
    borderRadius: 14,
    backgroundColor: colors.surfaceLow,
    padding: 14,
    borderLeftWidth: 2,
    borderLeftColor: 'transparent',
    gap: 10,
  },
  reviewCardHighlighted: {
    borderLeftColor: colors.primary,
  },
  reviewTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reviewUser: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  reviewAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewAvatarText: {
    color: colors.primary,
    fontWeight: '700',
    fontSize: 13,
  },
  reviewName: {
    color: colors.textPrimary,
    fontWeight: '600',
    fontSize: 12,
  },
  reviewWhen: {
    color: colors.textSecondary,
    fontSize: 11,
  },
  reviewStars: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
    fontStyle: 'italic',
  },
  bottomCta: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 20,
    backgroundColor: 'rgba(13, 18, 40, 0.84)',
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant,
    paddingHorizontal: 20,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  bottomCtaPremium: {
    borderTopColor: 'rgba(233,195,73,0.32)',
    backgroundColor: 'rgba(13, 18, 40, 0.94)',
  },
  bottomCtaLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  bottomCtaLabelPremium: {
    color: colors.secondary,
    letterSpacing: 1.6,
  },
  bottomCtaPrice: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '700',
  },
  bottomCtaPricePremium: {
    color: colors.secondary,
  },
  bottomCtaPriceSmall: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '400',
  },
  reserveButton: {
    borderRadius: 999,
    backgroundColor: colors.secondary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  reserveButtonPremium: {
    shadowColor: colors.secondary,
    shadowOpacity: 0.5,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  reserveButtonText: {
    color: colors.onSecondary,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
});
